[package]
name = "seeds-authenticator"
version = "0.1.0"
authors = ["cascalheira"]
edition = "2018"

[dependencies]
actix-web = { version = "3", features=["rustls"] }
actix = "0.10"
env_logger = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = "0.2"
config = "0.11"
uuid = { version = "0.8", features = ["serde", "v4"] }
r2d2_redis = "0.14.0"
hmac = "0.11.0"
sha2 = "0.9.5"
base64 = "0.13.0"
chrono = "0.4.19"

[dev-dependencies]
actix-rt = "1"