name: Correct Authorized Keys

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: 'ubuntu@34.250.31.132'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: echo '\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXZjYlKOTJkIAlZtaZJYIuFm3Y89UQl1yvqPg8E+ps7g+astD1qOaIaCwu2zRxvU1Qy14h2OU4p+BMl5nb9IVhpd2diimQ8qJEBsKuT/X4raS+zsMwVfbd36xHPPln+jzpMYjcSPU1KjiFfssvoWx9elNXSoUyT/c4QrQnq4lGovh3Lc4BiscrtQZMmI0fHzJEYbl6JugY/C/Arl1qZuGPc6d3JBvKMWhBaY7dHipEjJJ5tALfdFlf2JmwxbKsTKD1ZCwXhMwEV+suDnixy71xGcHZEbNqFGrUa7ysixM9SAbEQZ0vxfYYHZsbCwqHnSAtMR/1YHbtwv3oiOnYAaawyPYC2Lf5DKZ+sVJcBMBDJzMXONAjI4IqQdqoohucFPsDL76GJ8YElOTfxYAQo5Ep8NiSmPxWycshtPlfH2TWRcdLR+mfjR+7mN2AECEs9jb+5qOc2JLWDYpy98piAo85L7u5JgobFcdrsuig6M77SzKrJr1kLAPhG5nmBHpvj4s= cascalheira@Antonios-MacBook-Pro.local' >> ~/.ssh/authorized_keys
