name: Deploy to AWS
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          known_hosts: just-a-placeholder-so-we-dont-get-errors
      - name: Adding Known Hosts
        run: 'ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts'
      - name: Remove old files
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf /home/ubuntu/seeds/seeds-authenticator
          host: ${{ secrets.SSH_HOST }}
          user: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY}}
      - name: Deploy with rsync
        run: >-
          rsync -avz ${{ github.workspace }} ubuntu@${{ secrets.SSH_HOST
          }}:/home/ubuntu/seeds
      - name: Build rust
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu/seeds/seeds-authenticator
            cargo build --release
            cp -r ./config ./target/release
            mv ./target/release/config/environment-example.toml ./target/release/config/environment.toml
          host: ${{ secrets.SSH_HOST }}
          user: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY}}
